-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 22:13:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8mb4 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`ASSOCIADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`ASSOCIADOS` (
  `associados_id` INT NOT NULL AUTO_INCREMENT,
  `rg` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`associados_id`),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`TELEFONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`TELEFONES` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT,
  `id.associados` INT NOT NULL,
  `ddd` TINYINT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`telefone_id`),
  UNIQUE INDEX `rg_UNIQUE` (`id.associados` ASC) VISIBLE,
  CONSTRAINT `fk_id_associados`
    FOREIGN KEY (`id.associados`)
    REFERENCES `Biblioteca`.`ASSOCIADOS` (`associados_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`EDITORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`EDITORA` (
  `editora_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`editora_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`AUTOR` (
  `autor_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`autor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`LIVRO` (
  `livro_id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(30) NOT NULL,
  `titulo` VARCHAR(70) NOT NULL,
  `ano_publicacao` SMALLINT NOT NULL,
  `autor_id` INT NOT NULL,
  `editora_id` INT NOT NULL,
  `ano_escrito` SMALLINT NOT NULL,
  PRIMARY KEY (`livro_id`),
  UNIQUE INDEX `rg_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_id_editora_idx` (`editora_id` ASC) VISIBLE,
  INDEX `fk_autor_id_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_editora_id`
    FOREIGN KEY (`editora_id`)
    REFERENCES `Biblioteca`.`EDITORA` (`editora_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_id`
    FOREIGN KEY (`autor_id`)
    REFERENCES `Biblioteca`.`AUTOR` (`autor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`EMPRESTIMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`EMPRESTIMO` (
  `emprestimo_id` INT NOT NULL AUTO_INCREMENT,
  `associados_id` INT NOT NULL,
  `data_emprestimo` DATETIME NOT NULL,
  `prazo_devolucao` SMALLINT NOT NULL,
  `data_devolucao` DATETIME NOT NULL,
  PRIMARY KEY (`emprestimo_id`),
  INDEX `fk_associados_id_idx` (`associados_id` ASC) VISIBLE,
  CONSTRAINT `fk_associados_id`
    FOREIGN KEY (`associados_id`)
    REFERENCES `Biblioteca`.`ASSOCIADOS` (`associados_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`EXEMPLARES` (
  `exemplares_id` INT NOT NULL AUTO_INCREMENT,
  `livros_id` INT NOT NULL,
  `esta_danificado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`exemplares_id`),
  INDEX `fk_livros_id_idx` (`livros_id` ASC) VISIBLE,
  CONSTRAINT `fk_livros_id`
    FOREIGN KEY (`livros_id`)
    REFERENCES `Biblioteca`.`LIVRO` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`EMPRESTIMOS_EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`EMPRESTIMOS_EXEMPLARES` (
  `emprestimos_exemplares_id` INT NOT NULL AUTO_INCREMENT,
  `emprestimos_id` INT NOT NULL,
  `exemplares_id` INT NOT NULL,
  PRIMARY KEY (`emprestimos_exemplares_id`),
  INDEX `fk_emprestimos_id_idx` (`emprestimos_id` ASC) VISIBLE,
  INDEX `fk_exemplares_id_idx` (`exemplares_id` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimos_id`
    FOREIGN KEY (`emprestimos_id`)
    REFERENCES `Biblioteca`.`EMPRESTIMO` (`emprestimo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exemplares_id`
    FOREIGN KEY (`exemplares_id`)
    REFERENCES `Biblioteca`.`EXEMPLARES` (`exemplares_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
