-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 13:28:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Consultorio_saudeDH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Consultorio_saudeDH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Consultorio_saudeDH` DEFAULT CHARACTER SET utf8mb4 ;
USE `Consultorio_saudeDH` ;

-- -----------------------------------------------------
-- Table `Consultorio_saudeDH`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Consultorio_saudeDH`.`pacientes` (
  `pacientes_id` INT(11) NOT NULL,
  `paciente_idsaude` INT(11) NULL,
  `paciente_nome` VARCHAR(50) NULL,
  `paceinte_sobrenome` VARCHAR(100) NULL,
  PRIMARY KEY (`pacientes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Consultorio_saudeDH`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Consultorio_saudeDH`.`especialidades` (
  `especialidade_id` INT(11) NOT NULL,
  `especialidade_nome` VARCHAR(100) NULL,
  PRIMARY KEY (`especialidade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Consultorio_saudeDH`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Consultorio_saudeDH`.`medicos` (
  `medicos_id` INT(11) NOT NULL,
  `medico_nome` VARCHAR(40) NULL,
  `medico_sobrenome` VARCHAR(100) NULL,
  `medico_especialidade` INT(11) NULL,
  PRIMARY KEY (`medicos_id`),
  INDEX `fk_especialidadeID_idx` (`medico_especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_especialidadeID`
    FOREIGN KEY (`medico_especialidade`)
    REFERENCES `Consultorio_saudeDH`.`especialidades` (`especialidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Consultorio_saudeDH`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Consultorio_saudeDH`.`consultas` (
  `consulta_id` INT(11) NOT NULL,
  `paciente` INT(11) NULL,
  `medico` INT(11) NULL,
  `data_consulta` DATE NULL,
  `hora_consulta` TIME NULL,
  PRIMARY KEY (`consulta_id`),
  INDEX `fk_pacientesID_idx` (`paciente` ASC) VISIBLE,
  INDEX `fk_medicosID_idx` (`medico` ASC) VISIBLE,
  CONSTRAINT `fk_pacientesID`
    FOREIGN KEY (`paciente`)
    REFERENCES `Consultorio_saudeDH`.`pacientes` (`pacientes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicosID`
    FOREIGN KEY (`medico`)
    REFERENCES `Consultorio_saudeDH`.`medicos` (`medicos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
